eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true           //default true
    register-with-eureka: true     //default true
    service-url:
      defaultZone: http://localhost:8761/eureka
